/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import ad03.Alumno;
import ad03.myConnection;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class pagarCursos extends javax.swing.JFrame {

    ArrayList<String> cursosApagar = new ArrayList<>();
    int codigoAlumno;

    /**
     * Creates new form pagarCursos
     */
    public pagarCursos() {
        initComponents();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagarCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        cbAlumno.setModel(new DefaultComboBoxModel(obtenerAlumnos().toArray()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbAlumno = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtInfoNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCursosApagar = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btPagarCursos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pago de cursos");

        cbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlumnoActionPerformed(evt);
            }
        });

        jLabel1.setText("NIF Alumno");

        txtInfoNombre.setEditable(false);

        jLabel4.setText("Nombre del alumno");

        jScrollPane2.setViewportView(lstCursosApagar);

        jLabel2.setText("Cursos a pagar");

        btPagarCursos.setText("Pagar Curso/s");
        btPagarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagarCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(btPagarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtInfoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel2)))
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPagarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtInfoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addComponent(jLabel2)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlumnoActionPerformed

        //cargamos los datos del usuario que elijamos en el combobox
        String NIF = this.cbAlumno.getSelectedItem().toString();
        
        if (!NIF.equals("")) {
           
        Alumno alumno1 = obtenerDatosAlumno(NIF);
        cursosApagar.clear();//reseteamos la lista de nuevas matriculaciones
        codigoAlumno = alumno1.codAlumno;//fijamos el codigo de alumno del alumno elegido
        cursosApagar = alumno1.cursosApagar;//pasamos los cursos a pagar del alumno a la variable privada de la clase

        //rellenamos el nombre del alumno seleccionado
        txtInfoNombre.setText(alumno1.Nombre);

        //rellenamos la lista de cursos matriculados
        DefaultListModel model = new DefaultListModel();

        for (int i = 0, n = alumno1.cursosApagar.size(); i < n; i++) {
            model.addElement(alumno1.cursosApagar.get(i));
        }

        lstCursosApagar.setModel(model);
            
        }else{
            txtInfoNombre.setText("");
            DefaultListModel aux = (DefaultListModel) lstCursosApagar.getModel();
            aux.removeAllElements();
        }
        

    }//GEN-LAST:event_cbAlumnoActionPerformed

    private void btPagarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagarCursosActionPerformed

        int[] selectedItems = this.lstCursosApagar.getSelectedIndices();

        myConnection miConexion = new myConnection();

        if (selectedItems.length != 0) {

            String nombreCurso = null;

            for (int i = 0; i < selectedItems.length; i++) {

                nombreCurso = lstCursosApagar.getModel().getElementAt(selectedItems[i]);

                //**********************************************************************
                String sql = "UPDATE acadamel.matriculas SET Pagado = 1, Fecha_Pago = CURDATE() WHERE Codigo_Alumno = " + codigoAlumno + " AND Codigo_Curso = (SELECT Codigo_Curso FROM acadamel.cursos Where Nombre_Curso = '" + nombreCurso + "' LIMIT 1);";

                try {
                    miConexion.executeUpdate(sql);
                } catch (Exception e) {

                    System.err.println(e.getMessage());
                }

                //**********************************************************************

//                DefaultListModel model = (DefaultListModel) lstCursosApagar.getModel();
//                for (Object elem : lstCursosApagar.getSelectedValues()) {
//                    model.removeElement(elem);
//                }

            }

     
            //limpiamos la lista de asignaturas ¿OJO QUE ES DINAMICA! por eso he añadido un modificador de indice.
            int items_to_delete[] = null;
            items_to_delete = lstCursosApagar.getSelectedIndices();

             int modificador = 0;
            for (int i = 0; i < items_to_delete.length; i++) {
                
                DefaultListModel model = (DefaultListModel) lstCursosApagar.getModel();
                
                System.out.println(model.size()); 
                
                System.out.println("deleting: " + items_to_delete[i]);
                model.remove(items_to_delete[i] - modificador);
                
                modificador++;
            }

            
            
            

        }

        miConexion.closeConnection();

        JOptionPane.showMessageDialog(rootPane, "Se han pagado el curso o cursos seleccionados para el alumno " + cbAlumno.getSelectedItem().toString());

    }//GEN-LAST:event_btPagarCursosActionPerformed

    private ArrayList<String> obtenerAlumnos() {

        ArrayList<String> alumnos = new ArrayList<String>();
        alumnos.add("");

        //**********************************************************************
        myConnection miConexion = new myConnection();

        String sql
                = "SELECT NIF FROM acadamel.alumnos;";

        try {
            ResultSet rs = miConexion.executeSelect(sql);

            System.out.println(rs.getFetchSize());
            while (rs.next()) {

                //System.out.println(rs.getString("NIF"));  
                alumnos.add(rs.getString("NIF"));
            }

        } catch (Exception e) {

            System.err.println(e.getMessage());

        }
        miConexion.closeConnection();

        //**********************************************************************
        return alumnos;

    }

    //obtenemos los datos del alumno seleccionado
    private Alumno obtenerDatosAlumno(String NIF) {

        Alumno alum = new Alumno(NIF);

        //**********************************************************************
        myConnection miConexion = new myConnection();

        String sql = "SELECT * FROM acadamel.alumnos WHERE NIF = '" + NIF + "';";

        try {
            ResultSet rs = miConexion.executeSelect(sql);

            while (rs.next()) {

                System.out.println(rs.getString("Nombre_Alumno"));
                System.out.println(rs.getString("Codigo_Alumno"));

                alum.Nombre = rs.getString("Nombre_Alumno");
                alum.codAlumno = rs.getInt("Codigo_Alumno");

                break;
            }
        } catch (Exception e) {

            System.err.println(e.getMessage());

        }

        sql = "SELECT Nombre_Curso FROM acadamel.cursos, (SELECT Codigo_Curso FROM acadamel.matriculas Where Pagado = 0 AND Codigo_Alumno = " + alum.codAlumno + " ) as no_pagados WHERE  cursos.Codigo_Curso  = no_pagados.Codigo_Curso;";

        try {
            ResultSet rs = miConexion.executeSelect(sql);

            ArrayList<String> listaCursos = new ArrayList<String>();

            while (rs.next()) {

                System.out.println(rs.getString("Nombre_Curso"));

                listaCursos.add(rs.getString("Nombre_Curso"));
            }

            alum.cursosApagar = listaCursos;

        } catch (Exception e) {

            System.err.println(e.getMessage());

        }

        miConexion.closeConnection();

        //**********************************************************************
        return alum;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPagarCursos;
    private javax.swing.JComboBox<String> cbAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstCursosApagar;
    private javax.swing.JTextField txtInfoNombre;
    // End of variables declaration//GEN-END:variables
}
