/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import ad03.Alumno;
import ad03.myConnection;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class verDatosAlumnos extends javax.swing.JFrame {

    ArrayList<String> cursosMatriculados = new ArrayList<>();
    int codigoAlumno;

    /**
     * Creates new form pagarCursos
     */
    public verDatosAlumnos() {
        initComponents();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verDatosAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verDatosAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verDatosAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verDatosAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        cbAlumno.setModel(new DefaultComboBoxModel(obtenerAlumnos().toArray()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbAlumno = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCursosMatriculados = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btOk = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefonoAlumno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreoAlumno = new javax.swing.JTextField();
        txtPendientePago = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver datos alumnos");

        cbAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlumnoActionPerformed(evt);
            }
        });

        jLabel1.setText("NIF Alumno");

        jScrollPane2.setViewportView(lstCursosMatriculados);

        jLabel2.setText("Cursos Matriculados");

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre Alumno");

        txtNombreAlumno.setEditable(false);

        jLabel6.setText("Teléfono");

        txtTelefonoAlumno.setEditable(false);

        jLabel7.setText("Correo electrónico");

        txtCorreoAlumno.setEditable(false);

        txtPendientePago.setEditable(false);

        jLabel4.setText("Pendiente de pagar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(txtNombreAlumno)
                                .addComponent(txtTelefonoAlumno)
                                .addComponent(txtCorreoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(cbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPendientePago, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefonoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPendientePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btOk)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlumnoActionPerformed

        //cargamos los datos del usuario que elijamos en el combobox
        String NIF = this.cbAlumno.getSelectedItem().toString();

        if (!NIF.equals("")) {

            Alumno alumno1 = obtenerDatosAlumno(NIF);
            cursosMatriculados.clear();//reseteamos la lista de nuevas matriculaciones
            codigoAlumno = alumno1.codAlumno;//fijamos el codigo de alumno del alumno elegido
            cursosMatriculados = alumno1.cursosMatriculados;//pasamos los cursos matriculados del alumno a la variable privada de la clase

            //rellenamos los txt de informacion del alumno
            txtNombreAlumno.setText(alumno1.Nombre);
            txtTelefonoAlumno.setText(String.valueOf(alumno1.telefono));
            txtCorreoAlumno.setText(alumno1.correo);
            txtPendientePago.setText(String.valueOf(alumno1.pagoPendiente)+"\u20ac");

            //rellenamos la lista de cursos matriculados
            DefaultListModel model = new DefaultListModel();

            for (int i = 0, n = alumno1.cursosMatriculados.size(); i < n; i++) {
                model.addElement(alumno1.cursosMatriculados.get(i));
            }

            lstCursosMatriculados.setModel(model);

        } else {
            txtNombreAlumno.setText("");
            txtTelefonoAlumno.setText("");
            txtCorreoAlumno.setText("");
            txtPendientePago.setText("");
            DefaultListModel aux = (DefaultListModel) lstCursosMatriculados.getModel();
            aux.removeAllElements();
        }


    }//GEN-LAST:event_cbAlumnoActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed

        this.dispose();

    }//GEN-LAST:event_btOkActionPerformed

    private ArrayList<String> obtenerAlumnos() {

        ArrayList<String> alumnos = new ArrayList<String>();
        alumnos.add("");

        //**********************************************************************
        myConnection miConexion = new myConnection();

        String sql
                = "SELECT NIF FROM acadamel.alumnos;";

        try {
            ResultSet rs = miConexion.executeSelect(sql);

            System.out.println(rs.getFetchSize());
            while (rs.next()) {

                //System.out.println(rs.getString("NIF"));  
                alumnos.add(rs.getString("NIF"));
            }

        } catch (Exception e) {

            System.err.println(e.getMessage());

        }
        miConexion.closeConnection();

        //**********************************************************************
        return alumnos;

    }

    //obtenemos los datos del alumno seleccionado
    private Alumno obtenerDatosAlumno(String NIF) {

        Alumno alum = new Alumno(NIF);

        //**********************************************************************
        myConnection miConexion = new myConnection();

        String sql = "SELECT * FROM acadamel.alumnos WHERE NIF = '" + NIF + "';";

        try {
            ResultSet rs = miConexion.executeSelect(sql);

            while (rs.next()) {

                System.out.println(rs.getString("Nombre_Alumno"));
                System.out.println(rs.getString("Codigo_Alumno"));

                alum.Nombre = rs.getString("Nombre_Alumno");
                alum.codAlumno = rs.getInt("Codigo_Alumno");
                alum.telefono = rs.getInt("Telefono");
                alum.correo = rs.getString("Correo_electronico");

                break;
            }
        } catch (Exception e) {

            System.err.println(e.getMessage());

        }
        
        //*************

        sql = "SELECT Nombre_Curso FROM cursos, (SELECT Codigo_Curso FROM acadamel.matriculas Where Codigo_Alumno = " + alum.codAlumno + " ) as matriculadas WHERE  cursos.Codigo_Curso = matriculadas.Codigo_Curso;";

        try {
            ResultSet rs = miConexion.executeSelect(sql);

            ArrayList<String> listaCursos = new ArrayList<String>();

            while (rs.next()) {

                System.out.println(rs.getString("Nombre_Curso"));

                listaCursos.add(rs.getString("Nombre_Curso"));
            }

            alum.cursosMatriculados = listaCursos;

        } catch (Exception e) {

            System.err.println(e.getMessage());

        }
        
        //*************
        
        sql =  "SELECT SUM(Precio) as pendiente FROM acadamel.cursos, (SELECT Codigo_Curso FROM acadamel.matriculas WHERE Codigo_Alumno = "+ alum.codAlumno +" AND Pagado = 0) as asig_no_pay WHERE cursos.Codigo_Curso = asig_no_pay.Codigo_Curso;";

        try {
            ResultSet rs = miConexion.executeSelect(sql);

            ArrayList<String> listaCursos = new ArrayList<String>();

            while (rs.next()) {

                alum.pagoPendiente = rs.getInt("pendiente");
            }            

        } catch (Exception e) {

            System.err.println(e.getMessage());

        }

        miConexion.closeConnection();

        //**********************************************************************
        return alum;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOk;
    private javax.swing.JComboBox<String> cbAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstCursosMatriculados;
    private javax.swing.JTextField txtCorreoAlumno;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtPendientePago;
    private javax.swing.JTextField txtTelefonoAlumno;
    // End of variables declaration//GEN-END:variables
}
